spring:
  application:
    name: gotchai-server
  main:
    banner-mode: off
  profiles:
    include:
    - auth
    - oauth
    - rdb
    - redis
    - aws
    - logging
  web.resources.add-mappings: false
server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
  servlet:
    encoding:
      charset: UTF-8
      force: true
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod
