spring:
  cache:
    type: redis
---
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: ${REDIS_HOST}
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: ${REDIS_HOST}
